### PR TITLE
Run webapp components in a forked JVM

### LINKED ISSUE #960: Launch webappStart in a forked JVM
Currently, `webappStart` piggybacks off of sbt's JVM.  This is vulnerable to memory leaks and other crashes.  It will be more stable if we can fork it in a way similar to that of `warStart`.

This will take some doing:

1. Augment `com.heroku:webapp-runnner` so that it can:
    1. Run a webapp directly from its components, a la `WebappComponentsRunnerPlugin`
    1. Read its configuration from somewhere, e.g. a Java properties file under `target/`
1. Modify `WebappComponentsRunnerPlugin` to look more like `WarPackageRunnerPlugin`:
    1. Pull in the above augmented `webapp-runner`
    1. Write the configuration (port, resources, classes, lib, etc.) to a file
    1. Launch it in a forked JVM

Potential challenges:

* This will be slower than the current approach, because it takes time to spin up a forked JVM.  If this is too slow, it might not be worth the benefits.
* Maintaining the augmented `webapp-runner` will be a burden

References:

* https://github.com/earldouglas/webapp-components-runner

### PR DESCRIPTION
**Pull request by earldouglas**
This drops the webapp components runner in favor of com.earldouglas:webapp-components-runner to launch the webapp components in a forked JVM.

Fixes #960

### CODE REVIEW

File: src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala [hunk 1]
```diff
@@ -1,13 +1,18 @@
...
 import sbt._
 
+import java.nio.file.Files
+import java.nio.file.Paths
 import java.util.concurrent.atomic.AtomicReference
+import scala.sys.process.{Process => ScalaProcess}
 
-/** Launches the webapp composed of the resources, classes, and
-  * libraries specified by WebappComponentsPlugin.
+/** Launches the webapp file managed by WebappComponentsPlugin. Uses a
```
Comment (earldouglas) [inline src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala:13]: tyop

File: src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala [hunk 2]
```diff
@@ -17,63 +22,111 @@ object WebappComponentsRunnerPlugin extends AutoPlugin {
...
+            .mkString(",")
+
+        val configurationFile: File =
+          (Compile / target).value / "webapp-components.properties"
+
+        Files
+          .writeString(
+            Paths.get(configurationFile.getPath()),
+            s"""|hostname=localhost
+              |port=${webappPort.value}
```
Comment (earldouglas) [inline src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala:69]: formatting

File: src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala [hunk 3]
```diff
@@ -17,63 +22,111 @@ object WebappComponentsRunnerPlugin extends AutoPlugin {
...
       webappPort := 8080,
       webappStart := startWebapp.value,
       webappJoin := joinWebapp.value,
       webappStop := stopWebapp.value,
-      Global / onLoad := onLoadSetting.value
+      webappForkOptions := ForkOptions(),
+      Global / onLoad := onLoadSetting.value,
+      webappComponentsRunnerVersion := BuildInfo.webappComponentsRunnerVersion,
+      libraryDependencies ++=
+        Seq(
```
Comment (earldouglas) [inline src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala:126]: factor this out for readability?

File: build.sbt [hunk 4]
```diff
@@ -24,11 +24,21 @@ scalacOptions += s"-P:semanticdb:sourceroot:${baseDirectory.value}"
 lazy val webappRunnerVersion =
   settingKey[String]("webapp-runner version")
 webappRunnerVersion := "10.1.28.0"
-libraryDependencies += "com.heroku" % "webapp-runner" % webappRunnerVersion.value
+libraryDependencies += "com.heroku" % "webapp-runner" % webappRunnerVersion.value % Provided
+
+// webapp-components-runner
+lazy val webappComponentsRunnerVersion =
+  settingKey[String]("webapp-components-runner version")
+resolvers += "Sonatype OSS Staging" at "https://oss.sonatype.org/content/repositories/staging"
```
Comment (earldouglas) [inline build.sbt:32]: Drop once the release propagates to Maven Central.

File: src/template/build.sbt [hunk 5]
```diff
@@ -12,3 +12,5 @@ semanticdbEnabled := true
 semanticdbVersion := scalafixSemanticdb.revision
 
 scalacOptions += "-Wunused:all"
+
+resolvers += "Sonatype OSS Staging" at "https://oss.sonatype.org/content/repositories/staging"
```
Comment (earldouglas) [inline src/template/build.sbt:16]: Drop once the release propagates to Maven Central.
